name: manual_build

on:
  push:
    branches:
      - main

jobs:
  manual_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: "Build README.md"
        run: php run.php
      - name: "Commit changes"
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m ":robot: Build auto" || true
          git push